# Alacritty config file
[general]
live_config_reload = false
ipc_socket = false

[window]
title = "Alacritty"
dynamic_title = false
dimensions = { columns = 110, lines = 45 }

[font]
normal = { family = "MartianMonoNerdFontMono", style = "Regular" }
size = 11

[terminal]
shell = 'fish'

[mouse]
hide_when_typing = true

[bell]
color = "#ebb484"
animation = "EaseOut"
duration = 2

[colors]
# based on: https://github.com/vague2k/vague.nvim
primary.foreground = "#cdcdcd"
primary.background = "#141415"
selection = { text = "CellForeground", background = "#333738" }

[keyboard]
bindings = [
    # window management
    { key = "N", mods = "Control|Alt", action = "CreateNewWindow" },
    { key = "z", mods = "Control|Alt", action = "IncreaseFontSize" },
    { key = "h", mods = "Control|Alt", action = "DecreaseFontSize" },
    { key = "r", mods = "Control|Alt", action = "ResetFontSize" },
    # vi mode
    { key = "M", mods = "Control|Alt", action = "ToggleViMode" },
    { key = "q", mode = "Vi", action = "ToggleViMode" },
    # vi mode, work around some keyboard layout issues
    { key = "$", mode = "Vi", action = "Last" },
    { key = 13, mode = "Vi", action = "FirstOccupied" }, # binds ^
    # search mode
    { key = "s", mods = "Control|Alt", action = "SearchBackward" },
    { key = "q", mode = "Search", action = "SearchCancel" },
    { key = "c", mode = "Search", action = "SearchClear" },
    # fix numpad behavior (for nvim)
    { key = "Numpad1", chars = "1" },
    { key = "Numpad2", chars = "2" },
    { key = "Numpad3", chars = "3" },
    { key = "Numpad4", chars = "4" },
    { key = "Numpad5", chars = "5" },
    { key = "Numpad6", chars = "6" },
    { key = "Numpad7", chars = "7" },
    { key = "Numpad8", chars = "8" },
    { key = "Numpad9", chars = "9" },
]
