# Vague for Kitty
# -------------------
# Theme Author: vague2k <ilovedrawing056@gmail.com>
# Ported by:	skewb1k <skewb1kunix@gmail.com>
# License:  	MIT License
# Upstream: 	https://github.com/vague2k/vague.nvim/blob/main/extras/kitty/vague.conf
# modified: 	gerscha

foreground               #cdcdcd
background               #141415
background_opacity       1.0

selection_foreground     none
selection_background     none

#: The foreground and background colors for text selected with the
#: mouse. Setting both of these to none will cause a "reverse video"
#: effect for selections, where the selection will be the cell text
#: color and the text will become the cell background color. Setting
#: only selection_foreground to none will cause the foreground color
#: to be used unchanged. Note that these colors can be overridden by
#: the program running in the terminal.

cursor                   #cdcdcd
cursor_text_color        #cdcdcd

url_color                #bb9dbd

active_tab_foreground    #cdcdcd
active_tab_background    #141415
inactive_tab_foreground  #606079
inactive_tab_background  #252530

#: The color table {{{

#: The 256 terminal colors. There are 8 basic colors, each color has a
#: dull and bright version, for the first 16 colors. You can set the
#: remaining 240 colors as color16 to color255.

# black
color0   #000000
color8   #767676

# red
color1   #d8647e
color9   #e08398

# green
color2   #7fa563
color10  #99b782

# yellow
color3   #f3be7c
color11  #f5cb96

# blue
color4   #6e94b2
color12  #8ba9c1

# magenta
color5   #bb9dbd
color13  #c9b1ca

# cyan
color6   #aeaed1
color14  #bebeda

# white
color7   #cdcdcd
color15  #d7d7d7

#: }}}

# dynamic_background_opacity no

#: Allow changing of the background_opacity dynamically, using either
#: keyboard shortcuts (increase_background_opacity and
#: decrease_background_opacity) or the remote control facility.
#: Changing this option by reloading the config is not supported.
