monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
      },
      {
        node.name = "~alsa_input.*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
      }
    }
  }
]
