# remap prefix
set -g prefix C-f
unbind C-b

# switch panes 
bind h select-pane -L
unbind l # default: switch to previous active pane
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# split panes matching nvim
# bind s split-window -h
# bind v split-window -v
# unbind '"'
# unbind %
