### KEYBINDS ###
# separate out the keybinds into another file
source-file ~/.config/tmux/tmux.keybinds.conf



### CONFIG ###
# adjusted settings
set -g renumber-windows on # default is off
set -g base-index 1 # for keyboard layout this is better than default 0
set -g default-shell /bin/zsh
set -g history-limit 200000
set -g set-clipboard on # use system clipboard
set -g allow-rename off # don't rename windows automatically

set -s escape-time 20 #reduce time from 500 for faster ESC
set -g status-keys vi #editing the status bar
setw -g mode-keys vi #navigation in buffers

# Looks
set -g status-position top
# set -g pane-active-border-style 'fg=orange,bg=default'
# set -g pane-border-style 'fg=brightblack,bg=default'



### PLUGINS ###
  # trigger installation with 'prefix+I'
  # trigger updates with 'prefix+u'
  # trigger uninstall with 'prefix+alt+u'
# change the install path of plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/build/tmux/plugins/'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'erikw/tmux-powerline'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'


## Theme ##
set -g @plugin 'dracula/tmux'
# separate out the theme config
source-file ~/.config/tmux/tmux.theme.conf


## Plugin settings ##
set -g @continuum-restore 'on'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/build/tmux/tpm/tpm'
