# Vague theme
set -g status on
set -g status-position bottom
set -g status-interval 15
set -g status-left-length 100
set -g status-right-length 100

set -g status-justify absolute-centre

set -g status-style "fg=#cdcdcd,bg=#1c1c24"
set -g status-left "#[fg=#252530,bg=#aeaed1] #{?client_prefix,#[bg=#f3be7c],}\
#[bg=#aeaed1] #S #[fg=#cdcdcd,bg=#252530]   "
set -g status-right "#[fg=#cdcdcd,bg=#252530]   #[fg=#252530,bg=#aeaed1]  #H "

setw -g window-status-separator " "
setw -g window-status-format "#[fg=#252530,bg=#cdcdcd] #I #[fg=#cdcdcd,bg=#252530] #W#F "
setw -g window-status-current-format "#[fg=#252530,bg=#f3be7c] #I #[fg=#cdcdcd,bg=#252530] #W#F "

set -g message-style "fg=#cdcdcd,bg=#141415"

set -g display-panes-colour "#aeaed1"
set -g display-panes-active-colour "#f3be7c"

set -g pane-active-border-style 'fg=#878787,bg=default'
set -g pane-border-style 'fg=#252530,bg=default'
