### KEYBINDS ###
# switch panes vim style (in addition to arrow keys)
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind C-p previous-window
bind C-n next-window

bind R source-file ~/.config/tmux/tmux.conf

bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# prompt for a directory and set the current session's base directory
bind-key C command-prompt -p "New Session Base Directory:" "at -t . -c %%"

# splits inherit the current path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Plugin Manager Keybinds:
# trigger installation with 'prefix+I'
# trigger updates with 'prefix+u'
# trigger uninstall with 'prefix+alt+u'



### CONFIG ###
set -g renumber-windows on # default is off
set -g base-index 1 # for keyboard layout this is better than default 0
set -g default-shell ~/.local/share/cargo/bin/fish
set -g history-limit 20000
set -g display-time 1500
set -g set-clipboard on # use system clipboard
set -g allow-rename off # don't rename windows automatically
set -gq allow-passthrough on
set -s escape-time 100
set -g status-keys vi
set -g focus-events on # pass along focus events to applications
set -g mouse on
# Use vi-style key bindings in copy mode.
setw -g mode-keys vi
# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on


## Theme ##
source-file ~/.config/tmux/tmux.theme.conf


### PLUGINS ###
# auto install tpm
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm \
      && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
# set this manually to guarantee consistency accross different systems
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'noscript/tmux-mighty-scroll' # enable scroll in less, etc

## Plugin settings ##
set -g @continuum-restore 'on'
set -g @continuum-save-interval '0' # only manual saves

# set -g @resurrect-capture-pane-contents 'on'
# set -g @resurrect-processes 'false'
set -g @resurrect-processes 'nvim man less more tail top htop'
set -g @resurrect-strategy-nvim 'session'

set -g @mighty-scroll-interval 5


# Initialize plugin manager (must be last line)
run '~/.config/tmux/plugins/tpm/tpm'
